import type { Element, ElementContent, Root, RootContent } from "hast"
import {
  READING_RAIL_FOOTNOTE_SECTION_ID,
  READING_RAIL_LIMITS,
  READING_RAIL_METADATA_ID,
  ReadingRailEntryKind,
  type ReadingRailEntry,
  type ReadingRailModel,
} from "./types"

const SAFE_SOURCE_ID = /^[A-Za-z][A-Za-z0-9_.:%-]*$/
const MALFORMED_PERCENT_ENCODING = /%(?![0-9A-Fa-f]{2})/
const DECODED_CONTROL_CHARACTER = /[\u0000-\u001f\u007f-\u009f]/u
const SAFE_AUTHOR_ASIDE_ID = /^aside-[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/
const FOOTNOTE_ID_PREFIX = "user-content-fn-"
const FOOTNOTE_REFERENCE_ID_PREFIX = "user-content-fnref-"
const FOOTNOTE_MIRROR_ID_PREFIX = "reading-rail-mirror-"
const MAX_SOURCE_PATH_LENGTH = 1024
const TEXT_SEPARATOR_ELEMENTS = new Set([
  "address",
  "article",
  "aside",
  "blockquote",
  "br",
  "dd",
  "div",
  "dl",
  "dt",
  "figcaption",
  "figure",
  "footer",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "li",
  "main",
  "nav",
  "ol",
  "p",
  "pre",
  "section",
  "table",
  "td",
  "th",
  "tr",
  "ul",
])

interface LocatedElement {
  readonly element: Element
  readonly rootIndex: number
  readonly ancestors: readonly Element[]
}

interface FootnoteReference {
  readonly id: string
  readonly definitionId: string
  readonly rootIndex: number
  readonly label: string
  readonly expectedBackrefLabel: string
}

interface FootnoteDefinition {
  readonly element: Element
  readonly id: string
  readonly text: string
}

interface FootnoteMirror {
  readonly element: Element
  readonly entry: ReadingRailEntry
  readonly rootIndex: number
}

function fail(sourcePath: string, field: string, problem: string, correction: string): never {
  throw new Error(
    `Reading rail transform failed for "${sourcePath}" during HAST validation: ${field} ${problem}. ` +
      "Quartz cannot emit this article because its semantic reading rail would be ambiguous or inaccessible. " +
      `Fix: ${correction}.`,
  )
}

function validateSourcePath(sourcePath: string): void {
  if (
    sourcePath.trim().length === 0 ||
    sourcePath.length > MAX_SOURCE_PATH_LENGTH ||
    sourcePath.includes("\0")
  ) {
    fail(
      "<unknown source>",
      "source path",
      `must be a non-empty path of at most ${MAX_SOURCE_PATH_LENGTH} characters without NUL bytes`,
      "pass the Markdown file's repository-relative path to transformReadingRail",
    )
  }
}

function hasOwnProperty(element: Element, property: string): boolean {
  return Object.prototype.hasOwnProperty.call(element.properties, property)
}

function hasNormalizedProperty(
  element: Element,
  normalizedProperty: string,
  serializedProperty: string,
): boolean {
  return hasOwnProperty(element, normalizedProperty) || hasOwnProperty(element, serializedProperty)
}

function getNormalizedProperty(
  element: Element,
  normalizedProperty: string,
  serializedProperty: string,
): unknown {
  if (hasOwnProperty(element, normalizedProperty)) {
    return element.properties[normalizedProperty]
  }
  return element.properties[serializedProperty]
}

function getRequiredStringProperty(
  element: Element,
  property: string,
  sourcePath: string,
  field: string,
): string {
  const value = element.properties[property]
  if (typeof value !== "string" || value.length === 0) {
    fail(
      sourcePath,
      field,
      `must provide a non-empty string ${property} attribute`,
      `add a unique, stable ${property} value that uses only letters, numbers, period, colon, underscore, and hyphen`,
    )
  }
  return value
}

function validateEncodedId(
  id: string,
  maximumLength: number,
  sourcePath: string,
  field: string,
): void {
  if (
    id.length > maximumLength ||
    !SAFE_SOURCE_ID.test(id) ||
    MALFORMED_PERCENT_ENCODING.test(id)
  ) {
    fail(
      sourcePath,
      field,
      `has an unsafe or overlong id (maximum ${maximumLength} characters)`,
      "use a stable ID beginning with a letter and containing only letters, numbers, period, colon, underscore, hyphen, or well-formed percent-encoded bytes",
    )
  }

  if (id.includes("%")) {
    let decodedId: string
    try {
      decodedId = decodeURIComponent(id)
    } catch {
      fail(
        sourcePath,
        field,
        "contains invalid percent-encoded UTF-8",
        "use the exact percent-encoded ID generated by standard GFM from a valid Unicode footnote label",
      )
    }
    if (DECODED_CONTROL_CHARACTER.test(decodedId)) {
      fail(
        sourcePath,
        field,
        "decodes to a NUL or control character",
        "replace the footnote label with printable Unicode text and let GFM regenerate its ID",
      )
    }
  }
}

function validateSourceId(id: string, sourcePath: string, field: string): void {
  validateEncodedId(id, READING_RAIL_LIMITS.sourceIdLength, sourcePath, field)
}

function collectLocatedElements(tree: Root): LocatedElement[] {
  const located: LocatedElement[] = []

  function walk(element: Element, rootIndex: number, ancestors: readonly Element[]): void {
    located.push({ element, rootIndex, ancestors })
    const nextAncestors = [...ancestors, element]
    for (const child of element.children) {
      if (child.type === "element") walk(child, rootIndex, nextAncestors)
    }
  }

  tree.children.forEach((child, rootIndex) => {
    if (child.type === "element") walk(child, rootIndex, [])
  })
  return located
}

function readClassNames(element: Element, sourcePath: string, field: string): string[] {
  const className = element.properties.className
  if (className === undefined || className === null) return []
  if (typeof className === "string") return className.split(/\s+/).filter(Boolean)
  if (Array.isArray(className) && className.every((value) => typeof value === "string")) {
    return [...className]
  }
  fail(
    sourcePath,
    field,
    "has a malformed class attribute",
    "use a whitespace-separated HTML class string on the marked aside",
  )
}

function collectAccessibleTextWithoutBackrefs(node: Element | ElementContent): string {
  if (node.type === "text") return node.value
  if (node.type !== "element") return ""
  if (hasNormalizedProperty(node, "dataFootnoteBackref", "data-footnote-backref")) return ""
  if (node.tagName === "img") {
    const alt = node.properties.alt
    return typeof alt === "string" ? alt : ""
  }
  const text = node.children.map(collectAccessibleTextWithoutBackrefs).join("")
  return TEXT_SEPARATOR_ELEMENTS.has(node.tagName) ? ` ${text} ` : text
}

function normalizeMirrorText(text: string): string {
  return text.replace(/\s+/g, " ").trim()
}

function getRequiredNormalizedStringProperty(
  element: Element,
  normalizedProperty: string,
  serializedProperty: string,
  sourcePath: string,
  field: string,
): string {
  const value = getNormalizedProperty(element, normalizedProperty, serializedProperty)
  if (typeof value !== "string" || value.trim().length === 0) {
    fail(
      sourcePath,
      field,
      `must provide a non-empty ${serializedProperty} attribute`,
      `restore the ${serializedProperty} value generated by standard GFM`,
    )
  }
  return value
}

function getRequiredIdReferences(
  element: Element,
  normalizedProperty: string,
  serializedProperty: string,
  sourcePath: string,
  field: string,
): readonly string[] {
  const value = getNormalizedProperty(element, normalizedProperty, serializedProperty)
  const references =
    typeof value === "string"
      ? value.split(/\s+/).filter(Boolean)
      : Array.isArray(value) && value.every((item) => typeof item === "string")
        ? value
        : undefined
  if (references === undefined || references.length === 0) {
    fail(
      sourcePath,
      field,
      `must provide a ${serializedProperty} ID reference`,
      `restore the ${serializedProperty} relationship generated by standard GFM`,
    )
  }
  return references
}

function getFragmentTarget(element: Element, sourcePath: string, field: string): string {
  const href = getRequiredStringProperty(element, "href", sourcePath, field)
  if (!href.startsWith("#") || href.length === 1) {
    fail(
      sourcePath,
      field,
      "must use a same-document fragment href",
      "use standard GFM [^label] syntax so Quartz generates a matching #user-content-fn-* target",
    )
  }
  const target = href.slice(1)
  validateSourceId(target, sourcePath, field)
  return target
}

function freezeModel(
  entries: readonly ReadingRailEntry[],
  footnoteSectionId?: string,
): ReadingRailModel {
  const frozenEntries = Object.freeze(entries.map((entry) => Object.freeze({ ...entry })))
  return Object.freeze(
    footnoteSectionId === undefined
      ? { entries: frozenEntries }
      : { entries: frozenEntries, footnoteSectionId },
  )
}

function createMirror(
  reference: FootnoteReference,
  definition: FootnoteDefinition,
): FootnoteMirror {
  const id = `${FOOTNOTE_MIRROR_ID_PREFIX}${reference.id}`
  const entry = Object.freeze({
    kind: ReadingRailEntryKind.FootnoteMirror,
    id,
    referenceId: reference.id,
  })
  const element: Element = {
    type: "element",
    tagName: "aside",
    properties: {
      id,
      className: ["reading-rail-entry", "reading-rail-footnote-mirror"],
      dataReadingRailEntry: ReadingRailEntryKind.FootnoteMirror,
      dataReadingRailReference: reference.id,
      ariaHidden: "true",
    },
    children: [
      {
        type: "element",
        tagName: "span",
        properties: {
          className: ["reading-rail-footnote-number"],
          dataReadingRailNumber: reference.label,
        },
        children: [],
      },
      {
        type: "element",
        tagName: "span",
        properties: {
          className: ["reading-rail-footnote-text"],
          dataReadingRailText: definition.text,
        },
        children: [],
      },
    ],
  }
  return { element, entry, rootIndex: reference.rootIndex }
}

export function transformReadingRail(tree: Root, sourcePath: string): ReadingRailModel {
  validateSourcePath(sourcePath)
  const located = collectLocatedElements(tree)
  const knownIds = new Map<string, Element>()

  for (const { element } of located) {
    if (!hasOwnProperty(element, "id")) continue
    const id = getRequiredStringProperty(element, "id", sourcePath, `${element.tagName} id`)
    if (knownIds.has(id)) {
      fail(
        sourcePath,
        `${element.tagName} id`,
        `uses duplicate ID "${id}"`,
        "give every heading, aside, footnote reference, and footnote definition a unique ID",
      )
    }
    knownIds.set(id, element)
  }

  const authorAsides: LocatedElement[] = []
  const asideClassNames = new Map<Element, readonly string[]>()
  for (const item of located) {
    const { element, ancestors } = item
    if (hasNormalizedProperty(element, "dataReadingRailEntry", "data-reading-rail-entry")) {
      fail(
        sourcePath,
        "data-reading-rail-entry",
        "is reserved for generated rail entries",
        "remove this attribute and use data-reading-aside only on authored semantic asides",
      )
    }
    if (!hasNormalizedProperty(element, "dataReadingAside", "data-reading-aside")) continue

    if (element.tagName !== "aside") {
      fail(
        sourcePath,
        "data-reading-aside marker",
        "must be attached to a semantic aside element",
        'replace the marked element with <aside data-reading-aside id="aside-...">',
      )
    }
    const marker = getNormalizedProperty(element, "dataReadingAside", "data-reading-aside")
    if (marker !== "" && marker !== true) {
      fail(
        sourcePath,
        "data-reading-aside marker",
        "must be a valueless semantic marker",
        "write data-reading-aside without assigning it a value",
      )
    }
    if (ancestors.length > 0) {
      fail(
        sourcePath,
        "marked author aside",
        "is nested instead of being a top-level article block",
        "move the marked aside beside its related top-level paragraph and never nest marked asides",
      )
    }

    const id = getRequiredStringProperty(element, "id", sourcePath, "marked author aside id")
    validateSourceId(id, sourcePath, "marked author aside id")
    if (!SAFE_AUTHOR_ASIDE_ID.test(id)) {
      fail(
        sourcePath,
        "marked author aside id",
        "must begin with aside- and use lowercase hyphen-separated words",
        "choose an ID such as aside-method-context",
      )
    }
    asideClassNames.set(element, readClassNames(element, sourcePath, `marked author aside "${id}"`))
    authorAsides.push(item)
  }

  if (authorAsides.length > READING_RAIL_LIMITS.authorAsides) {
    fail(
      sourcePath,
      "author aside collection",
      `exceeds the static limit of ${READING_RAIL_LIMITS.authorAsides}`,
      `reduce this article to at most ${READING_RAIL_LIMITS.authorAsides} marked asides`,
    )
  }

  const footnoteSections = located.filter(({ element }) =>
    hasNormalizedProperty(element, "dataFootnotes", "data-footnotes"),
  )
  for (const { element } of footnoteSections) {
    if (element.tagName !== "section") {
      fail(
        sourcePath,
        "data-footnotes marker",
        "must identify a canonical section element",
        "author footnotes with standard GFM [^label] syntax instead of raw footnote markup",
      )
    }
  }
  if (footnoteSections.length > 1) {
    fail(
      sourcePath,
      "canonical footnote section",
      "appears more than once",
      "keep one standard GFM footnote definition list per Markdown article",
    )
  }

  const referenceItems = located.filter(({ element }) =>
    hasNormalizedProperty(element, "dataFootnoteRef", "data-footnote-ref"),
  )
  const backrefItems = located.filter(({ element }) =>
    hasNormalizedProperty(element, "dataFootnoteBackref", "data-footnote-backref"),
  )
  if (referenceItems.length > READING_RAIL_LIMITS.footnoteReferences) {
    fail(
      sourcePath,
      "footnote reference collection",
      `exceeds the static limit of ${READING_RAIL_LIMITS.footnoteReferences}`,
      `reduce this article to at most ${READING_RAIL_LIMITS.footnoteReferences} GFM footnote references`,
    )
  }
  if (backrefItems.length > READING_RAIL_LIMITS.footnoteBackrefs) {
    fail(
      sourcePath,
      "footnote backref collection",
      `exceeds the static limit of ${READING_RAIL_LIMITS.footnoteBackrefs}`,
      `restore standard GFM output with exactly one backref for each of at most ${READING_RAIL_LIMITS.footnoteReferences} noterefs`,
    )
  }

  const footnoteSectionItem = footnoteSections[0]
  if (footnoteSectionItem === undefined) {
    if (referenceItems.length > 0 || backrefItems.length > 0) {
      fail(
        sourcePath,
        "canonical footnote section",
        "is missing while footnote references or backrefs are present",
        "define every [^label] with a matching [^label]: entry and let GFM generate the section",
      )
    }

    const totalEntries = 1 + authorAsides.length
    if (totalEntries > READING_RAIL_LIMITS.entries) {
      fail(
        sourcePath,
        "reading rail entry collection",
        `exceeds the static limit of ${READING_RAIL_LIMITS.entries}`,
        "reduce the number of marked author asides",
      )
    }
    for (const { element } of authorAsides) {
      element.properties.className = [
        ...new Set([
          ...(asideClassNames.get(element) ?? []),
          "reading-rail-entry",
          "reading-rail-author-aside",
        ]),
      ]
      element.properties.dataReadingRailEntry = ReadingRailEntryKind.AuthorAside
    }
    tree.children = tree.children.filter(
      (child) => child.type !== "text" || child.value.trim().length > 0,
    )
    return freezeModel([
      { kind: ReadingRailEntryKind.Metadata, id: READING_RAIL_METADATA_ID },
      ...authorAsides.map(({ element }) => ({
        kind: ReadingRailEntryKind.AuthorAside,
        id: getRequiredStringProperty(element, "id", sourcePath, "marked author aside id"),
      })),
    ])
  }

  const { element: footnoteSection, ancestors: footnoteSectionAncestors } = footnoteSectionItem
  if (footnoteSectionAncestors.length > 0) {
    fail(
      sourcePath,
      "canonical footnote section",
      "is nested instead of being a top-level article section",
      "use standard GFM footnote definitions at the document root",
    )
  }

  const footnoteLabels = footnoteSection.children.filter(
    (child): child is Element => child.type === "element" && child.tagName === "h2",
  )
  if (footnoteLabels.length !== 1) {
    fail(
      sourcePath,
      "canonical footnote label",
      "must contain exactly one in-section h2 label",
      "restore the screen-reader label generated by standard GFM instead of hand-authoring the footnote section",
    )
  }
  const footnoteLabel = footnoteLabels[0]
  const footnoteLabelId = getRequiredStringProperty(
    footnoteLabel,
    "id",
    sourcePath,
    "canonical footnote label id",
  )
  validateSourceId(footnoteLabelId, sourcePath, "canonical footnote label id")
  if (!readClassNames(footnoteLabel, sourcePath, "canonical footnote label").includes("sr-only")) {
    fail(
      sourcePath,
      "canonical footnote label",
      "must retain the GFM sr-only class",
      "restore the screen-reader-only h2 emitted by standard GFM",
    )
  }
  if (
    normalizeMirrorText(collectAccessibleTextWithoutBackrefs(footnoteLabel)).length === 0 ||
    getNormalizedProperty(footnoteLabel, "ariaHidden", "aria-hidden") === "true" ||
    getNormalizedProperty(footnoteLabel, "ariaHidden", "aria-hidden") === true
  ) {
    fail(
      sourcePath,
      "canonical footnote label",
      "must expose non-empty text to assistive technology",
      "restore the visible-to-assistive-technology label generated by standard GFM",
    )
  }

  const orderedLists = footnoteSection.children.filter(
    (child): child is Element => child.type === "element" && child.tagName === "ol",
  )
  if (orderedLists.length !== 1) {
    fail(
      sourcePath,
      "canonical footnote section",
      "must contain exactly one ordered definition list",
      "remove raw footnote markup and use standard GFM [^label] definitions",
    )
  }
  const definitionElements = orderedLists[0].children.filter(
    (child): child is Element => child.type === "element" && child.tagName === "li",
  )
  if (definitionElements.length > READING_RAIL_LIMITS.footnoteDefinitions) {
    fail(
      sourcePath,
      "footnote definition collection",
      `exceeds the static limit of ${READING_RAIL_LIMITS.footnoteDefinitions}`,
      `reduce this article to at most ${READING_RAIL_LIMITS.footnoteDefinitions} GFM footnote definitions`,
    )
  }
  if (definitionElements.length === 0) {
    fail(
      sourcePath,
      "canonical footnote section",
      "contains no footnote definitions",
      "remove the empty raw section or add standard GFM footnote definitions",
    )
  }

  const definitions = new Map<string, FootnoteDefinition>()
  for (const definition of definitionElements) {
    const id = getRequiredStringProperty(definition, "id", sourcePath, "footnote definition id")
    validateSourceId(id, sourcePath, "footnote definition id")
    if (!id.startsWith(FOOTNOTE_ID_PREFIX)) {
      fail(
        sourcePath,
        "footnote definition id",
        `does not use the standard ${FOOTNOTE_ID_PREFIX} prefix`,
        "author the definition with GFM [^label]: syntax",
      )
    }
    const text = normalizeMirrorText(collectAccessibleTextWithoutBackrefs(definition))
    if (text.length === 0) {
      fail(
        sourcePath,
        `footnote definition "${id}"`,
        "has no accessible text or image alt text to mirror",
        "add explanatory text or meaningful image alt text to the GFM footnote definition",
      )
    }
    if (text.length > READING_RAIL_LIMITS.mirrorTextLength) {
      fail(
        sourcePath,
        `footnote definition "${id}"`,
        `exceeds the visual mirror text limit of ${READING_RAIL_LIMITS.mirrorTextLength} characters`,
        "shorten the footnote while retaining the complete canonical explanation within the declared limit",
      )
    }
    definitions.set(id, { element: definition, id, text })
  }

  const references: FootnoteReference[] = []
  const referencesById = new Map<string, FootnoteReference>()
  const referenceOccurrences = new Map<string, number>()
  for (const { element, ancestors, rootIndex } of referenceItems) {
    if (element.tagName !== "a") {
      fail(
        sourcePath,
        "footnote noteref",
        "must be an anchor element",
        "use standard GFM [^label] syntax and do not hand-author data-footnote-ref",
      )
    }
    if (ancestors.includes(footnoteSection)) {
      fail(
        sourcePath,
        "footnote noteref",
        "is nested inside the canonical footnote section",
        "place [^label] references in article prose, outside the definition list",
      )
    }
    const id = getRequiredStringProperty(element, "id", sourcePath, "footnote noteref id")
    validateSourceId(id, sourcePath, "footnote noteref id")
    if (!id.startsWith(FOOTNOTE_REFERENCE_ID_PREFIX)) {
      fail(
        sourcePath,
        "footnote noteref id",
        `does not use the standard ${FOOTNOTE_REFERENCE_ID_PREFIX} prefix`,
        "author the reference with GFM [^label] syntax",
      )
    }
    const definitionId = getFragmentTarget(element, sourcePath, `footnote noteref "${id}"`)
    if (!definitions.has(definitionId)) {
      fail(
        sourcePath,
        `footnote noteref "${id}"`,
        `points to unresolved definition "${definitionId}"`,
        "add the matching GFM footnote definition or correct the reference label",
      )
    }
    const describedBy = getRequiredIdReferences(
      element,
      "ariaDescribedBy",
      "aria-describedby",
      sourcePath,
      `footnote noteref "${id}"`,
    )
    if (describedBy.length !== 1 || describedBy[0] !== footnoteLabelId) {
      fail(
        sourcePath,
        `footnote noteref "${id}" aria-describedby`,
        `must reference only the canonical in-section label "${footnoteLabelId}"`,
        "restore the aria-describedby relationship generated by standard GFM",
      )
    }
    const label = normalizeMirrorText(collectAccessibleTextWithoutBackrefs(element))
    if (label.length === 0) {
      fail(
        sourcePath,
        `footnote noteref "${id}"`,
        "has no visible reference label",
        "use standard GFM footnote syntax so the noteref receives a number",
      )
    }
    if (label.length > READING_RAIL_LIMITS.mirrorNumberLength) {
      fail(
        sourcePath,
        `footnote noteref "${id}"`,
        `has a visual label above ${READING_RAIL_LIMITS.mirrorNumberLength} characters`,
        "use standard GFM footnote syntax with its bounded generated numeric label",
      )
    }
    const occurrence = (referenceOccurrences.get(definitionId) ?? 0) + 1
    referenceOccurrences.set(definitionId, occurrence)
    const expectedBackrefLabel = `Back to reference ${label}${occurrence === 1 ? "" : `-${occurrence}`}`
    const reference = { id, definitionId, rootIndex, label, expectedBackrefLabel }
    references.push(reference)
    referencesById.set(id, reference)
  }

  for (const definition of definitions.values()) {
    if (!references.some((reference) => reference.definitionId === definition.id)) {
      fail(
        sourcePath,
        `footnote definition "${definition.id}"`,
        "has no matching noteref",
        "remove the unused raw definition or add a standard GFM [^label] reference",
      )
    }
  }

  const backrefCounts = new Map<string, number>()
  for (const { element, ancestors } of backrefItems) {
    if (element.tagName !== "a" || !ancestors.includes(footnoteSection)) {
      fail(
        sourcePath,
        "footnote backref",
        "must be an anchor inside the canonical footnote section",
        "let GFM generate backrefs instead of hand-authoring data-footnote-backref",
      )
    }
    const referenceId = getFragmentTarget(element, sourcePath, "footnote backref")
    const reference = referencesById.get(referenceId)
    if (reference === undefined) {
      fail(
        sourcePath,
        "footnote backref",
        `points to unresolved noteref "${referenceId}"`,
        "restore the matching GFM noteref or regenerate the footnote from Markdown",
      )
    }
    const owningDefinition = [...definitions.values()].find(({ element: definition }) =>
      ancestors.includes(definition),
    )
    if (owningDefinition === undefined || reference.definitionId !== owningDefinition.id) {
      fail(
        sourcePath,
        "footnote backref",
        "points to a noteref for a different definition",
        "regenerate the footnote relationships with matching GFM labels",
      )
    }
    const ariaLabel = getRequiredNormalizedStringProperty(
      element,
      "ariaLabel",
      "aria-label",
      sourcePath,
      `footnote backref to "${referenceId}"`,
    )
    if (ariaLabel !== reference.expectedBackrefLabel) {
      fail(
        sourcePath,
        `footnote backref to "${referenceId}" aria-label`,
        `must equal "${reference.expectedBackrefLabel}"`,
        "restore the accessible backref label generated by standard GFM",
      )
    }
    const count = (backrefCounts.get(referenceId) ?? 0) + 1
    if (count > 1) {
      fail(
        sourcePath,
        `footnote backref to "${referenceId}"`,
        "must have exactly one accessible backref for its noteref",
        "remove duplicate raw backrefs and let standard GFM generate one return link",
      )
    }
    backrefCounts.set(referenceId, count)
  }
  for (const reference of references) {
    if (backrefCounts.get(reference.id) !== 1) {
      fail(
        sourcePath,
        `footnote noteref "${reference.id}"`,
        "must have exactly one accessible canonical backref",
        "restore the single GFM backref so keyboard readers can return to the reference",
      )
    }
  }

  const existingFootnoteSectionId = hasOwnProperty(footnoteSection, "id")
    ? getRequiredStringProperty(footnoteSection, "id", sourcePath, "canonical footnote section id")
    : undefined
  if (existingFootnoteSectionId !== undefined) {
    validateSourceId(existingFootnoteSectionId, sourcePath, "canonical footnote section id")
  } else if (knownIds.has(READING_RAIL_FOOTNOTE_SECTION_ID)) {
    fail(
      sourcePath,
      "canonical footnote section id",
      `cannot reserve "${READING_RAIL_FOOTNOTE_SECTION_ID}" because another element uses it`,
      "rename the authored element that collides with the generated canonical section ID",
    )
  }
  const footnoteSectionId = existingFootnoteSectionId ?? READING_RAIL_FOOTNOTE_SECTION_ID

  const mirrors: FootnoteMirror[] = []
  for (const reference of references) {
    const definition = definitions.get(reference.definitionId)
    if (definition === undefined) {
      fail(
        sourcePath,
        `footnote noteref "${reference.id}"`,
        "lost its validated definition before mirror generation",
        "rerun the build without another transform mutating GFM footnotes",
      )
    }
    const mirror = createMirror(reference, definition)
    validateEncodedId(
      mirror.entry.id,
      READING_RAIL_LIMITS.generatedIdLength,
      sourcePath,
      `footnote mirror for "${reference.id}"`,
    )
    if (knownIds.has(mirror.entry.id)) {
      fail(
        sourcePath,
        `footnote mirror for "${reference.id}"`,
        `collides with existing ID "${mirror.entry.id}"`,
        "rename the authored element using the reserved reading-rail-mirror-* prefix",
      )
    }
    knownIds.set(mirror.entry.id, mirror.element)
    mirrors.push(mirror)
  }

  const totalEntries = 1 + authorAsides.length + mirrors.length
  if (totalEntries > READING_RAIL_LIMITS.entries) {
    fail(
      sourcePath,
      "reading rail entry collection",
      `exceeds the static limit of ${READING_RAIL_LIMITS.entries}`,
      "reduce the combined number of marked asides and GFM footnote references",
    )
  }

  for (const { element } of authorAsides) {
    element.properties.className = [
      ...new Set([
        ...(asideClassNames.get(element) ?? []),
        "reading-rail-entry",
        "reading-rail-author-aside",
      ]),
    ]
    element.properties.dataReadingRailEntry = ReadingRailEntryKind.AuthorAside
  }
  footnoteSection.properties.id = footnoteSectionId

  const mirrorsByRootIndex = new Map<number, Element[]>()
  for (const mirror of mirrors) {
    const atIndex = mirrorsByRootIndex.get(mirror.rootIndex) ?? []
    atIndex.push(mirror.element)
    mirrorsByRootIndex.set(mirror.rootIndex, atIndex)
  }
  const transformedChildren: RootContent[] = []
  tree.children.forEach((child, rootIndex) => {
    if (child.type !== "text" || child.value.trim().length > 0) transformedChildren.push(child)
    transformedChildren.push(...(mirrorsByRootIndex.get(rootIndex) ?? []))
  })
  tree.children = transformedChildren

  const entries: ReadingRailEntry[] = [
    { kind: ReadingRailEntryKind.Metadata, id: READING_RAIL_METADATA_ID },
  ]
  for (const child of tree.children) {
    if (child.type !== "element") continue
    const kind = child.properties.dataReadingRailEntry
    const id = child.properties.id
    if (kind === ReadingRailEntryKind.AuthorAside && typeof id === "string") {
      entries.push({ kind, id })
    } else if (kind === ReadingRailEntryKind.FootnoteMirror && typeof id === "string") {
      const referenceId = child.properties.dataReadingRailReference
      if (typeof referenceId === "string") entries.push({ kind, id, referenceId })
    }
  }

  return freezeModel(entries, footnoteSectionId)
}
